'use strict';

function buildEmailHtml({ studioName, clientName, businessName, budget, briefText }) {
  const esc = str => str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const bodyHtml = briefText.split('\n').map(line => {
    const t = line.trim();
    if (!t) return '<div style="height:10px"></div>';
    if (/^\d+[\.:]\s+\S/.test(t)) {
      return `<h2 style="font-family:Georgia,serif;font-size:17px;font-weight:700;color:#0f172a;background:#f1f5f9;padding:9px 14px;margin:32px 0 14px;border-left:3px solid #3b82f6">${esc(t)}</h2>`;
    }
    return `<p style="font-size:15px;line-height:1.9;color:#334155;font-family:Georgia,serif;margin:0 0 14px">${esc(t)}</p>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Web Design Brief — ${esc(studioName)}</title></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:Helvetica Neue,Arial,sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#fff;border-radius:6px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08)">
        <tr><td style="background:#0f172a;padding:36px 48px">
          <p style="margin:0 0 10px;font-size:10px;letter-spacing:.28em;text-transform:uppercase;color:#64748b">${esc(studioName)}</p>
          <h1 style="margin:0;font-family:Georgia,serif;font-size:34px;font-weight:400;color:#f8fafc;line-height:1.15">Web Design Brief</h1>
        </td></tr>
        <tr><td style="background:#f8fafc;padding:18px 48px;border-bottom:1px solid #e2e8f0">
          <p style="margin:0;font-size:13px;color:#64748b;line-height:1.8">
            <strong style="color:#0f172a">${esc(clientName)}</strong>
            &nbsp;·&nbsp;${esc(businessName)}&nbsp;·&nbsp;${esc(budget)}
          </p>
        </td></tr>
        <tr><td style="padding:36px 48px 24px">${bodyHtml}</td></tr>
        <tr><td style="padding:16px 48px 28px;border-top:1px solid #e2e8f0">
          <p style="margin:0;font-size:11px;color:#94a3b8;letter-spacing:.06em">Generated by ${esc(studioName)}</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function buildDesignerNotificationEmail({ studioName, acc, clientName, clientEmail, businessName, industry, budget, pageCount, briefUrl }) {
  const esc = s => (s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>New Brief — ${esc(studioName)}</title></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:Helvetica Neue,Arial,sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px"><tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#fff;border-radius:6px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08)">
<tr><td style="background:${esc(acc)};padding:32px 48px">
  <p style="margin:0 0 8px;font-size:10px;letter-spacing:.28em;text-transform:uppercase;color:#fff;opacity:.75">${esc(studioName)}</p>
  <h1 style="margin:0;font-family:Georgia,serif;font-size:26px;font-weight:400;color:#fff;line-height:1.2">New Brief Ready</h1>
</td></tr>
<tr><td style="padding:32px 48px 0">
  <p style="margin:0 0 4px;font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:#94a3b8">Client</p>
  <p style="margin:0 0 4px;font-size:20px;font-family:Georgia,serif;color:#0f172a">${esc(clientName)}</p>
  ${clientEmail ? `<a href="mailto:${esc(clientEmail)}" style="font-size:13px;color:${esc(acc)};text-decoration:none">${esc(clientEmail)}</a>` : ''}
  <div style="height:1px;background:#e2e8f0;margin:20px 0"></div>
</td></tr>
<tr><td style="padding:0 48px">
  <table width="100%" cellpadding="0" cellspacing="0">
    ${businessName ? `<tr><td style="padding-bottom:12px;border-bottom:1px solid #f1f5f9"><span style="font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#94a3b8">Business</span><p style="margin:3px 0 0;font-size:14px;color:#334155">${esc(businessName)}</p></td></tr>` : ''}
    ${industry ? `<tr><td style="padding:12px 0;border-bottom:1px solid #f1f5f9"><span style="font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#94a3b8">Industry</span><p style="margin:3px 0 0;font-size:14px;color:#334155">${esc(industry)}</p></td></tr>` : ''}
    ${budget ? `<tr><td style="padding:12px 0;border-bottom:1px solid #f1f5f9"><span style="font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#94a3b8">Budget</span><p style="margin:3px 0 0;font-size:14px;color:#334155">${esc(budget)}</p></td></tr>` : ''}
    ${pageCount ? `<tr><td style="padding:12px 0"><span style="font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#94a3b8">Pages</span><p style="margin:3px 0 0;font-size:14px;color:#334155">${esc(pageCount)}</p></td></tr>` : ''}
  </table>
</td></tr>
<tr><td style="padding:28px 48px 40px;text-align:center">
  <a href="${esc(briefUrl)}" style="display:inline-block;background:${esc(acc)};color:#fff;text-decoration:none;padding:13px 32px;border-radius:4px;font-size:11px;letter-spacing:.16em;text-transform:uppercase">View Brief</a>
</td></tr>
<tr><td style="padding:14px 48px 22px;border-top:1px solid #e2e8f0">
  <p style="margin:0;font-size:11px;color:#94a3b8;letter-spacing:.06em">${esc(studioName)} — brief notification</p>
</td></tr>
</table></td></tr></table>
</body></html>`;
}

async function sendEmail(payload) {
  const html    = buildEmailHtml(payload);
  const subject = `Your Web Design Brief — ${payload.studioName}`;
  const from    = process.env.EMAIL_FROM || `${payload.studioName} <noreply@mail.debrieft.app>`;
  const targets = [payload.clientEmail, payload.designerEmail].filter(Boolean);

  if (process.env.RESEND_API_KEY) {
    const { Resend } = require('resend');
    const resend = new Resend(process.env.RESEND_API_KEY);
    const results = await Promise.all(targets.map(to => resend.emails.send({ from, to, subject, html })));
    const errors = results.map(r => r.error).filter(Boolean);
    if (errors.length) {
      const msg = errors.map(e => e.message || JSON.stringify(e)).join('; ');
      throw new Error(`Resend error: ${msg}`);
    }
    return { sent: true, count: targets.length };
  }

  return { sent: false, reason: 'email_disabled' };
}

module.exports = { buildEmailHtml, buildDesignerNotificationEmail, sendEmail };
